Repo configurations branch
gemy-97/C_plus_plus pull request #1
Opened 2023-03-03 14:11 UTC by Mjamal-ubuntu

Adding README file with description & modifiying .gitignore file

2023-03-05 22:08 UTC, gemy-97 requested changes
I think we need to align with each other, how the README file will be updated in organized way.

2023-03-05 22:08 UTC, gemy-97 commented on README.md
> +hacckerrank folder will be made to solve all the problems in hacckerrank site.
I see another PR creating the hacker rank folder so, I think this file will need to be updated within the second PR.

2023-03-06 22:22 UTC, Mjamal-ubuntu commented on README.md
> +hacckerrank folder will be made to solve all the problems in hacckerrank site.
done , the README file updated

2023-03-06 22:38 UTC, gemy-97 approved these changes
looks fine to me , approved

2023-03-06 22:39 UTC, merged

2023-03-06 22:39 UTC, gemy-97 commented
PR done